<div class="container-fluid">
                            <div class="box box-primary">
                                                        <div class="box-header with-border">
                            <h3 class="box-title">Your Action : Accept payment & issuance permit.</h3>
                            <div class="box-tools pull-right">
<!--                                 <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                                </button>
                               <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>-->
                            </div>
                        </div>
                        <form role="form" id="submitform" name="submitform" action="/admin/permitpendingpayment/evp_submit/" method="POST">
<div class="box-body">
<div class="form-group">
<label for="picremark">PIC Remark</label>
<div>
<?php echo ($permit_apply_remark?$permit_apply_remark:"<i>- No Remark -</i>");?>
</div>
</div>

<!--
                                    <div class="form-group">
                                        <label for="serialno">Driving Permit Serial No <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup> <?php echo form_error('serialno') ?></label>
                                        <input class="form-control" type="text" name="serialno" id="serialno" readonly value="<?php echo $issuance_serial_no;?>"><i><span style="font-size: x-small">autogenerated</span></i>
                                    </div>
-->
                                    <?php /* ?>
                                    <div class="form-group">
                                        <label for="engineCapacity">Engine Capacity <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup> <?php echo form_error('engineCapacity') ?></label>
                                        <input class="form-control"  type="text" name="engineCapacity" id="engineCapacity" readonly value="<?php echo $capacity_name_txt;?>">
                                    </div>
                                    <?php */ ?>

<div class="row">
    <div class="col-md-6">
    <h3>Payment Detail</h3>

                                    <div class="form-group">

                                        <label for="startdate">Permit start date <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup> <?php echo form_error('startdate') ?></label>
                                        <input type="text" name="startdate" id="startdate" value="<?php echo date('d-m-Y');?>" class="datepicker_local form-control">
                                    </div>
                                    <div class="form-group">
                                        <label for="expirydate">Permit expiry Date <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup> <?php echo form_error('expirydate') ?></label>
                                        <input type="text" name="expirydate" id="expirydate" value="<?php echo date('d-m-Y', strtotime('+1 year -1 day'));?>" class="datepicker_local form-control">


                                    </div>
<!--
                                    <div class="form-group">
                                        <label for="receiptno">Receipt No <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup> <?php echo form_error('receiptno') ?></label>
                                        <input class="form-control" type="text" name="receiptno" id="receiptno" value="<?php echo $receiptno;?>" readonly >
                                    </div>
-->
                                    <div class="form-group" style="display: none;">
                                        <label for="fee_training">Fee (Training) </label>
                                        <input class="form-control" type="text" name="fee_training" id="fee_training" value="">
                                    </div>
                                    <div class="form-group">
                                        <label for="fee_new">Payment Location <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup> </label>
                                        <span class="form-control">
                                            <label class="radio-inline"><input type="radio" name="payment_location" class="payment_location" value="KLIA" checked>KLIA</label>
                                            <label class="radio-inline"><input type="radio" name="payment_location" class="payment_location" value="KLIA2">KLIA2</label>
                                        </span>
                                    </div>
                                    <div class="form-group">
                                        <label for="fee_new">Payment Method <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup> </label>
                                        <span class="form-control">
                                            <label class="radio-inline"><input type="radio" name="payment_method" value="1" checked>Cash</label>
                                            <label class="radio-inline"><input type="radio" name="payment_method" value="2">Cheque</label>
                                            <label class="radio-inline"><input type="radio" name="payment_method" value="3">Credit Facilities</label>
                                            <label class="radio-inline"><input type="radio" name="payment_method" value="4">Free of Charges</label>
                                        </span>
                                    </div>
                                    <div class="form-group cheque_div" >
                                        <label for="fee_new">Cheque No / Reference No </label>
                                        <input class="form-control"  type="text" name="ref_cheque_no" id="ref_cheque_no" value="">
                                    </div>
                                    <div class="form-group">
                            <label for="fee_new">Payment Type <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup> </label>
                            <span class="form-control">
                                            <label class="radio-inline"><input type="radio" name="payment_type" class="payment_type" value="1" checked>One year Permit</label>
                                            <label class="radio-inline"><input type="radio" name="payment_type" class="payment_type" value="2">Pro-rated Permit</label>
                                            <!-- added on 7 Oct 2021 -->
                                            <label class="radio-inline"><input type="radio" name="payment_type" class="payment_type" value="3">Replacement Permit</label>
                                        </span>
                        </div>
                                    <div class="form-group">
                                        <label for="fee_new">Fee <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup> <?php echo form_error('fee_new') ?></label>
                                        <input class="form-control" type="text" name="fee_new" id="fee_new" readonly="" value="<?=$capacity_price_txt?>" class="">
                                            <input id="inclusive_sst" style="display: none;" name="inclusive_sst" type="checkbox" value="y" checked><span style="display: none;"> inclusive sst </span>

                                    </div>

<!--                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Fee (Renew Application) <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup> <?php echo form_error('fee_renew') ?></label>
                                        <label for="exampleInputEmail1">

                                         <select id="renewtype" name="renewtype" size="1">
    <option value="1year" selected="selected">1 Year</option>
    <option value="prorated">Pro-Rated</option>
    </select>: <input type="text" name="fee_renew" id="fee_renew" value="" class=""> <input id="inclusive_sst_renew" name="inclusive_sst_renew" type="checkbox" value="y" checked><span> inclusive sst </span></label>
                                    </div>-->
<!--                                    <div class="form-group">
                                        <label for="approvaldate">Action Date <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup><?php echo form_error('approvaldate') ?></label>
                                        <input type="text" name="approvaldate" id="approvaldate" readonly value="<?php echo date('Y-m-d H:i:s');?>">
                                    </div>-->
    </div>
    <div class="col-md-6">
    <h3>Others</h3>

                                    <div class="form-group">
                                        <label for="companyname_permit">Company Name (Permit) <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup> <?php echo form_error('companyname_permit') ?></label>
                                        <input type="text" name="companyname_permit" id="companyname_permit" value="<?php echo $permit_companyid;?>" class="form-control">
                                    </div>

                                    <div class="form-group">
                                        <label for="companyname_receipt">Company Name (Receipt) <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup> <?php echo form_error('companyname_receipt') ?></label>
                                        <input type="text" name="companyname_receipt" id="companyname_receipt" value="<?php echo $permit_companyid;?>" class="form-control">
                                    </div>

                                    <div class="form-group">
                                        <label for="remark"><h3>Remark</h3></label>
                                        <textarea class="form-control" id="remark" name="remark"></textarea>
                                    </div>
    </div>
</div>



                                <div class="form-group">
                                    <!-- <label for="agree">proclamation</label><br> -->
                                    <input id="agree" name="agree" type="checkbox" value="y"> I hereby confirm that the information provided herein is accurate, correct and complete and that the documents submitted along with this application form are genuine.  <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup><?php echo form_error('agree') ?>
                                </div>

                                <input id="submit" name="submit" type="submit" value="Submit" class="btn btn-primary">
                                <input type="hidden" name="approvaldate" id="approvaldate" value="<?php echo date('Y-m-d H:i:s');?>">
                                <input type="hidden" name="permit_id" id="permit_id" value="<?php echo $permit_id; ?>">
                                <input type="hidden" name="permit_condition" id="permit_condition" value="<?php echo $permit_condition; ?>">

                            </div>
                        </form>
                    </div>
                </div>
<script>
$(document).ready(function() {
        $('.payment_type').trigger('change');
        $('.payment_type').on('change', function() {
            var pt = $('input[name=payment_type]:checked').val();
            if (pt == 1) {
                $('#fee_new').val('24.00').prop('readonly', true);
            }
            else if (pt == 2) {
                $('#fee_new').val('0').prop('readonly', false);
            }
            else {
                $('#fee_new').val('5.00').prop('readonly', false);
            }
        });
    $('.cheque_div').hide();
    $('input[name="payment_method"]').on('click',function(){
        var checked_val = $('input[name="payment_method"]:checked').val();
        if(checked_val == 4)
        {
            $('#fee_new').val('0');
            $('.cheque_div').hide();
        }
        else if(checked_val == 2)
        {
            $('.cheque_div').show('200');
        }
        else
        {
            $('#fee_new').val('<?=$capacity_price_txt?>');
            $('.cheque_div').hide();
        }
    });

    $( ".datepicker" ).datepicker({
        dateFormat: 'dd-mm-yy'
    });

    $('#startdate').on('change',function(){
        var sd = str = $(this).val();
        console.log('sd',sd);

        var parts = str.split("-");

        var day = parts[0] && parseInt( parts[0], 10 );
        var month = parts[1] && parseInt( parts[1], 10 );
        var year = parts[2] && parseInt( parts[2], 10 );
        var duration = parseInt( '1', 10);

        if( day <= 31 && day >= 1 && month <= 12 && month >= 1 ) {

            var expiryDate = new Date( year, month - 1, day -1);
            expiryDate.setFullYear( expiryDate.getFullYear() + duration );

            var day = ( '0' + expiryDate.getDate() ).slice( -2 );
            var month = ( '0' + ( expiryDate.getMonth() + 1 ) ).slice( -2 );
            var year = expiryDate.getFullYear();

            $("#expirydate").val( day + "-" + month + "-" + year );
            console.log('ed',day + "-" + month + "-" + year);

        } else {
            // display error message
        }
    });
    
$('html,body').animate({scrollTop: document.body.scrollHeight},"slow");
});
</script>