<div class="container-fluid">
                            <div class="box box-primary">
                                                        <div class="box-header with-border">
                            <h3 class="box-title">Your Action : Accept payment & issuance permit.</h3>
                            <div class="box-tools pull-right">
<!--                                 <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                                </button>
                               <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>-->
                            </div>
                        </div>
                        <form role="form" id="submitform" name="submitform" action="/admin/permitpendingpayment/avp_submit/" method="POST">                     <div class="box-body">

                                    <div class="form-group">
                                        <label for="serialno">Driving Permit Serial No <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup> <?php echo form_error('serialno') ?></label>
                                        <input class="form-control"  type="text" name="serialno" id="serialno" readonly value="<?php echo $issuance_serial_no;?>"><i><span style="font-size: x-small">autogenerated</span></i>
                                    </div>
                                    <div class="form-group">
                                        <label for="engineCapacity">Engine Capacity <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup> <?php echo form_error('engineCapacity') ?></label>
                                        <input class="form-control"  type="text" name="engineCapacity" id="engineCapacity" readonly value="<?php echo $capacity_name_txt;?>">
                                    </div>
                                    <div class="form-group">
                                        <label for="startdate">Date of permit issuance <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup> <?php echo form_error('startdate') ?></label>
                                        <input type="text" name="startdate" id="startdate" value="<?php echo date('Y-m-d');?>" class="datepicker form-control">
                                    </div>
                                    <div class="form-group">
                                        <label for="expirydate">Permit expiry Date <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup> <?php echo form_error('expirydate') ?></label>
                                        <input type="text" name="expirydate" id="expirydate" value="<?php echo date('Y-m-d', strtotime('+1 year'));?>" class="datepicker form-control">
                                    </div>
                                    <div class="form-group">
                                        <label for="receiptno">Receipt No <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup> <?php echo form_error('receiptno') ?></label>
                                        <input class="form-control"  type="text" name="receiptno" id="receiptno" value="" class="">
                                    </div>
                                    <div class="form-group">
                                        <label for="fee_training">Fee (Training) </label>
                                        <input class="form-control"  type="text" name="fee_training" id="fee_training" value="" class="">
                                        
                                    </div>
                                    <div class="form-group">
                                        <label for="fee_new">Fee (New Application) <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup> <?php echo form_error('fee_new') ?></label>
                                        <input class="form-control"  type="text" name="fee_new" id="fee_new" readonly="" value="<?=$capacity_price_txt?>" class="">
                                            <input id="inclusive_sst" name="inclusive_sst" type="checkbox" value="y" checked><span> inclusive sst </span>
                                        
                                    </div>
<!--                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Fee (Renew Application) <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup> <?php echo form_error('fee_renew') ?></label>
                                        

                                         <select id="renewtype" name="renewtype" size="1">
    <option value="1year" selected="selected">1 Year</option>
    <option value="prorated">Pro-Rated</option>
    </select>: <input type="text" name="fee_renew" id="fee_renew" value="" class=""> <input id="inclusive_sst_renew" name="inclusive_sst_renew" type="checkbox" value="y" checked><span> inclusive sst </span>
                                    </div>-->
<!--                                    <div class="form-group">
                                        <label for="approvaldate">Action Date <sup><span class="glyphicon glyphicon-star text-danger" aria-hidden="true"></span></sup><?php echo form_error('approvaldate') ?></label>
                                        <input class="form-control"  type="text" name="approvaldate" id="approvaldate" readonly value="<?php echo date('Y-m-d H:i:s');?>">
                                    </div>-->
                                    <div class="form-group">
                                        <label for="remark">Remark</label>
                                        <textarea class="form-control" id="remark" name="remark"></textarea>
                                    </div>
                                <div class="form-group">
                                    <label for="agree">proclamation</label><br>
                                    <input id="agree" name="agree" type="checkbox" value="y"> I hereby confirm<?php echo form_error('agree') ?>
                                </div>

                                <input id="submit" name="submit" type="submit" value="Submit" class="btn btn-primary">


                                <input type="hidden" name="approvaldate" id="approvaldate" value="<?php echo date('Y-m-d H:i:s');?>">
                                <input type="hidden" name="permit_id" id="permit_id" value="<?php echo $permit_id; ?>">
                                <input type="hidden" name="permit_condition" id="permit_condition" value="<?php echo $permit_condition; ?>">

                            </div>
                        </form>
                    </div>
                </div>